# Generated by Django 3.0.3 on 2020-03-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200220_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
