# Generated by Django 3.0.3 on 2020-03-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='stars',
        ),
    ]
